# Generated by Django 5.1.2 on 2024-11-14 13:17

import django.utils.timezone
import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('original_url', models.URLField(max_length=1000)),
                ('status', models.PositiveIntegerField(choices=[(0, 'CONVERTED'), (1, 'PENDING'), (2, 'FAILED')], default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('short_code', models.CharField(default=shortener.models.generate_short_code, max_length=6, unique=True)),
            ],
        ),
    ]
