# Generated by Django 5.1.2 on 2024-12-18 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('original_url', models.URLField(max_length=1000)),
                ('url_bytes', models.BinaryField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('short_code', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
