# Generated by Django 5.1.2 on 2024-10-31 14:41

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('complate_link', models.URLField(max_length=100)),
                ('status', models.PositiveIntegerField(choices=[(0, 'CONVERTED'), (1, 'PENDING'), (2, 'FAILED')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short_code', models.CharField(default=shortener.models.generate_short_code, max_length=10, unique=True)),
            ],
        ),
    ]
