# Generated by Django 5.1.2 on 2024-10-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='complate_link',
        ),
    ]
